spring:
  datasource:
    url: jdbc:mysql://localhost:33606/palette
    username: palette
    password: palette
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    cachePrepStmts: true
    prepStmtCacheSize: 100
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    maximumPoolSize: 10
    
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /
      suffix: .jsp
      
  cache:
    ehcache:
      config: classpath:ehcache.xml

  security:
    enabled: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG
        security: DEBUG

cafe24:
  client:
    mallId: {{mall_id}}
    # App이 가진 클라이언트 아이디(사용자에게 노출)
    clientId: D0OdNNlzFdfWprppcum7NG
    # app이 가진 비밀키(노출되지 않음)
    clientSecret: aSks6QrRPBEhyqDtG9LQlA
    # AccessToken 요청 URI
    accessTokenUri: https://{{mall_id}}.cafe24api.com/api/v2/oauth/token
    # ClientCode 요청 URI
    userAuthorizationUri: https://{{mall_id}}.cafe24api.com/api/v2/oauth/authorize
    # AccessToken 요청 방식: header, query
    authorizationScheme: header
    # ClientCode 요청 방식: header, form, query
    clientAuthenticationScheme: header
    # redirect_uri 파라미터 추가, default : true
    useCurrentUri: false
    # code 발급 후 redirect 되는 URI
    preEstablishedRedirectUri: https://devbit005.cafe24.com/mammoth/oauth2
    scope: 
      - mall.read_application,mall.write_application,mall.read_design,mall.write_design,mall.read_order,mall.write_order,mall.read_product,mall.write_product,mall.read_store,mall.write_store
  resource:
    #API 리소스 서버 uri
    userInfoUri: https://{{mall_id}}.cafe24api.com/api/v2/admin/store