# Commons properties
# 로컬 JUnit 테스트를 위해 값을 모두 입력하였음.
# 다른 사람은 수정하여 사용하길 바람.
spring:
  # 실행 profile 설정
  profiles:
    active:
    - dev

  datasource:
    url: jdbc:mysql://lee33397.cafe24.com:3306/devbit005
    driver-class-name: com.mysql.jdbc.Driver
    username: devbit005
    password: devbit005
    #type: org.apache.tomcat.jdbc.pool.DataSource
    
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

logging:
  level:
    org:
      springframework:
        web: INFO
        http: INFO
        security: INFO
        
cafe24:
  client:
    # App이 가진 클라이언트 아이디(사용자에게 노출)
    clientId: PLJ3LsIxIdkkcvwiEjejoH
    # app이 가진 비밀키(노출되지 않음)
    clientSecret: WI0AD13hJpugDMUfOMN11H
    # AccessToken 요청 URI
    accessTokenUri: https://{{mall_id}}.cafe24api.com/api/v2/oauth/token
    # ClientCode 요청 URI
    userAuthorizationUri: https://{{mall_id}}.cafe24api.com/api/v2/oauth/authorize
    # AccessToken 요청 방식: header, query
    authorizationScheme: header
    # ClientCode 요청 방식: header, form, query
    clientAuthenticationScheme: header
    # redirect_uri 파라미터 추가, default : true
    useCurrentUri: false
    
    # code 발급 후 redirect 되는 URI
    preEstablishedRedirectUri: https://lee33397.cafe24.com/securityOAuth2/oauth2
    
    scope:
      - mall.read_application,mall.write_application,mall.read_store,mall.write_store
  resource:
    #API 리소스 서버 uri
    userInfoUri: https://{{mall_id}}.cafe24api.com/api/v2/admin/store
    
    # API 리소스 ADMIN API uri
    admin: https://{{mall_id}}.cafe24api.com/api/v2/admin
    
    # API 리소드 FRONT API uri
    front: https://{{mall_id}}.cafe24.com/api/v2/