# Commons properties
# 로컬 JUnit 테스트를 위해 값을 모두 입력하였음.
# 다른 사람은 수정하여 사용하길 바람.
spring:
  # 실행 profile 설정
#  profiles:
#    active:
#    - dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    open-in-view: true

  mvc:
    view:
      prefix: /views/
      suffix: .jsp