# Commons properties
spring:
  # 실행 profile 설정
  profiles:
    active:
    - dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #type: org.apache.tomcat.jdbc.pool.DataSource

  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

logging:
  level:
    org:
      springframework:
        web: INFO
        http: INFO
        security: INFO